# Dockerfile

# Usando uma imagem do Node.js como base
FROM node:16-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia o package.json e package-lock.json para instalar as dependências
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install --legacy-peer-deps

# Força a instalação de uma versão específica do ajv
RUN npm install ajv@6.12.6

# Copia o restante do código para o diretório de trabalho
COPY . .

# Expõe a porta 3000
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
