# Usar a imagem base do Python
FROM python:3.10

# Definir o diretório de trabalho
WORKDIR /app

# Instalar dependências do sistema e o curl
RUN apt-get update -y && \
    apt-get install -y postgresql-client

# Copiar todos os arquivos do diretório atual para /app no contêiner
COPY . /app

# Instalar as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta onde o app vai rodar
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "app.py"]
